def con2014Q ( ) :
    import os
    import time
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import sys
    import struct
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import sys
    import os
    import sys
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import sys
    BAD = string
    CHEAT = string
    import string
    import string
    import sys
    from ..exceptions import InvalidWarning
    from ..util import InvalidWarning
    from ..util import InvalidWarning
    from ..util import InvalidWarning
    from ..util import InvalidWarning
    from ..util import InvalidWarning
    from ..util import InvalidWarning
    from ..util import InvalidWarning
    from ..util import InvalidWarning
    from ..util import InvalidWarning
    from ..util import InvalidWarning
    from .util import InvalidWarning
    from .util import InvalidWarning
    from .util import InvalidWarning
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
    from .util import MakeError
